---
server:
    install: '1'
    packages: [vim, git, htop, nodejs, npm, imagemagick]
    timezone: Europe/London
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.37, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: rsync }
apache:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
mariadb:
    install: '1'
    root_password: '123'
    database: db
    user: user
    password: password
    dump: ''
solr:
    install: '1'
    port: '8983'
    version: 5.2.0
    cloud_mode: '0'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-gd, php5-common, php5-fpm, php5-mysql]
xdebug:
    install: '1'
composer:
    install: '1'

php7_configure_string: --prefix=/usr/local/php7 --enable-bcmath --with-bz2 --enable-calendar --enable-exif --enable-dba --enable-ftp --with-gettext --with-gd --enable-mbstring --with-mcrypt --with-mhash --enable-mysqlnd --with-mysql=mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-openssl --enable-pcntl --with-pspell --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --with-zlib --enable-zip --with-readline --with-curl
php7_cli_configure_string: --with-config-file-path=/etc/php7/cli --with-config-file-scan-dir=/etc/php7/cli/conf.d
